FROM centos:7

RUN yum update -y && \
    yum install -y \
    epel-release \
    libaio \
    wget \
    nano \
    && yum clean all

RUN yum install -y yum-utils


RUN wget --no-check-certificate -O /tmp/mysql.tar.gz https://downloads.mysql.com/archives/get/p/23/file/mysql-XXX-x86_64.tar.gz && \
    tar -xf /tmp/mysql.tar.gz -C /usr/local/ && \
    mv /usr/local/mysql-XXX-x86_64 /usr/local/mysql && \
    rm /tmp/mysql.tar.gz

ENV PATH="/usr/local/mysql/bin:${PATH}"


RUN groupadd mysql \
    && useradd -r -g mysql -s /bin/false mysql

RUN mkdir -p /var/lib/mysql && \
    chown -R mysql:mysql /usr/local/mysql && \
    chown -R mysql:mysql /var/lib/mysql

COPY my.cnf /etc/my.cnf

RUN /usr/local/mysql/scripts/mysql_install_db --user=mysql --basedir=/usr/local/mysql --datadir=/var/lib/mysql --tmpdir=/var/tmp

 CMD ["/usr/local/mysql/bin/mysqld"]

